# Generated by Django 3.1.4 on 2020-12-09 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_auto_20201210_0136'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='oreder_number',
            new_name='order_number',
        ),
    ]
