# Generated by Django 3.1.4 on 2020-12-10 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_auto_20201210_0137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery_number',
            old_name='time',
            new_name='order_number',
        ),
    ]
